Fix building with musl libc
On musl lib fseeko64 is not supported, and building on musl gives the
following error:

In file included from util.h:10,
                 from device_file.c:9:
device_file.c: In function 'DeviceFile_ReadContigious':
oscompatibility.h:159:46: error: implicit declaration of function 'fseeko64'; did you mean 'fseeko'? [-Wimplicit-function-declaration]
  159 | #define _fseeki64(f, o, w)                  (fseeko64(f, o, w))
      |                                              ^~~~~~~~
device_file.c:197:13: note: in expansion of macro '_fseeki64'
  197 |     if(0 == _fseeki64(ctx->File[0].h, ctxRC->paBase, SEEK_SET)) {
      |             ^~~~~~~~~

For now I've wrapped the definitions around #ifdef's, so that fseeko64
and other similar fucntions are only used under GLIBC and on musl we can
use the supported fseeko (and other supported) functions. But I'm open
to better approach as this could lead to macro hell.

First reported on Gentoo Linux on musl profile. Please refer:
https://bugs.gentoo.org/935917

Signed-off-by: Brahmajit Das <brahmajit.xyz@gmail.com>